// Generated by Better Auth CLI. Do not edit manually.

import {
  boolean,
  integer,
  pgTable,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  email_verified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),

  twitter_id: text("twitter_id").unique(),
  twitter_username: text("twitter_username"),
  twitter_bio: text("twitter_bio"),
  twitter_location: text("twitter_location"),
  twitter_banner_url: text("twitter_banner_url"),
  twitter_url: text("twitter_url"),
  twitter_verified: boolean("twitter_verified").default(false),
  twitter_verified_type: text("twitter_verified_type"),
  twitter_created_at: timestamp("twitter_created_at"),
  avatar_url: text("avatar_url"),
  twitter_synced_at: timestamp("twitter_synced_at"),

  twitter_followers: integer("twitter_followers").default(0),
  twitter_following: integer("twitter_following").default(0),
  twitter_tweet_count: integer("twitter_tweet_count").default(0),
  twitter_listed_count: integer("twitter_listed_count").default(0),
  twitter_verified_followers: integer("twitter_verified_followers").default(0),
  twitter_followers_count: integer("twitter_followers_count").default(0),

  role: text("role"),
  onboarding_completed: boolean("onboarding_completed").default(false),
  has_creator_profile: boolean("has_creator_profile").default(false),
  has_sponsor_profile: boolean("has_sponsor_profile").default(false),

  creator_status: text("creator_status"),
  creator_price_min: integer("creator_price_min"),
  creator_price_max: integer("creator_price_max"),
  creator_categories: text("creator_categories"),
  creator_looking_for: text("creator_looking_for"),
  creator_contact_method: text("creator_contact_method"),
  creator_contact_value: text("creator_contact_value"),

  sponsor_status: text("sponsor_status"),
  sponsor_company_name: text("sponsor_company_name"),
  sponsor_company_website: text("sponsor_company_website"),
  sponsor_industry: text("sponsor_industry"),
  sponsor_categories: text("sponsor_categories"),
  sponsor_budget_min: integer("sponsor_budget_min"),
  sponsor_budget_max: integer("sponsor_budget_max"),
  sponsor_looking_for: text("sponsor_looking_for"),
});

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expires_at: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
  ip_address: text("ip_address"),
  user_agent: text("user_agent"),
  user_id: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
});

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  account_id: text("account_id").notNull(),
  provider_id: text("provider_id").notNull(),
  user_id: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  access_token: text("access_token"),
  refresh_token: text("refresh_token"),
  id_token: text("id_token"),
  access_token_expires_at: timestamp("access_token_expires_at"),
  refresh_token_expires_at: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expires_at: timestamp("expires_at").notNull(),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
});



